### PR TITLE
Compute Taylor coefficient for conformal map

### PR DESCRIPTION
**Pull request by navidcy**
Using the script in `sandbox` with `r = 1 - 1e-7` we get:

```Julia
[ Info: After 30 iterations we have:
k =  1, A ≈ +1.47713062600964, A_Rancic = +1.47713062600964, |A - A_Rancic| = 6.66e-16 
k =  2, A ≈ -0.38183510510173, A_Rancic = -0.38183510510174, |A - A_Rancic| = 5.16e-15 
k =  3, A ≈ -0.05573058001191, A_Rancic = -0.05573058001191, |A - A_Rancic| = 4.16e-16 
k =  4, A ≈ -0.00895883606818, A_Rancic = -0.00895883606818, |A - A_Rancic| = 3.86e-15 
k =  5, A ≈ -0.00791315785221, A_Rancic = -0.00791315785221, |A - A_Rancic| = 1.79e-15 
k =  6, A ≈ -0.00486625437708, A_Rancic = -0.00486625437708, |A - A_Rancic| = 4.53e-15 
k =  7, A ≈ -0.00329251751279, A_Rancic = -0.00329251751279, |A - A_Rancic| = 1.43e-15 
k =  8, A ≈ -0.00235481488325, A_Rancic = -0.00235481488325, |A - A_Rancic| = 5.84e-16 
k =  9, A ≈ -0.00175870527475, A_Rancic = -0.00175870527475, |A - A_Rancic| = 3.22e-15 
k = 10, A ≈ -0.00135681133278, A_Rancic = -0.00135681133278, |A - A_Rancic| = 3.08e-15 
k = 11, A ≈ -0.00107459847699, A_Rancic = -0.00107459847699, |A - A_Rancic| = 1.44e-15 
k = 12, A ≈ -0.00086944475948, A_Rancic = -0.00086944475948, |A - A_Rancic| = 9.24e-16 
k = 13, A ≈ -0.00071607115121, A_Rancic = -0.00071607115121, |A - A_Rancic| = 3.76e-15 
k = 14, A ≈ -0.00059867100093, A_Rancic = -0.00059867100093, |A - A_Rancic| = 1.12e-15 
k = 15, A ≈ -0.00050699063239, A_Rancic = -0.00050699063239, |A - A_Rancic| = 2.57e-15 
k = 16, A ≈ -0.00043415191279, A_Rancic = -0.00043415191279, |A - A_Rancic| = 2.95e-15 
k = 17, A ≈ -0.00037541003286, A_Rancic = -0.00037541003286, |A - A_Rancic| = 1.50e-15 
k = 18, A ≈ -0.00032741060099, A_Rancic = -0.00032741060100, |A - A_Rancic| = 5.16e-15 
k = 19, A ≈ -0.00028773091481, A_Rancic = -0.00028773091482, |A - A_Rancic| = 5.41e-15 
k = 20, A ≈ -0.00025458777519, A_Rancic = -0.00025458777519, |A - A_Rancic| = 3.96e-15 
k = 21, A ≈ -0.00022664642371, A_Rancic = -0.00022664642371, |A - A_Rancic| = 3.97e-15 
k = 22, A ≈ -0.00020289261022, A_Rancic = -0.00020289261022, |A - A_Rancic| = 3.25e-15 
k = 23, A ≈ -0.00018254510830, A_Rancic = -0.00018254510830, |A - A_Rancic| = 2.39e-15 
k = 24, A ≈ -0.00016499474460, A_Rancic = -0.00016499474461, |A - A_Rancic| = 1.03e-14 
k = 25, A ≈ -0.00014976117167, A_Rancic = -0.00014976117168, |A - A_Rancic| = 6.64e-15 
k = 26, A ≈ -0.00013646173947, A_Rancic = -0.00013646173946, |A - A_Rancic| = 1.21e-14 
k = 27, A ≈ -0.00012478875822, A_Rancic = -0.00012478875823, |A - A_Rancic| = 1.08e-14 
k = 28, A ≈ -0.00011449267279, A_Rancic = -0.00011449267279, |A - A_Rancic| = 1.56e-15 
k = 29, A ≈ -0.00010536946150, A_Rancic = -0.00010536946150, |A - A_Rancic| = 2.65e-15 
k = 30, A ≈ -0.00009725109375, A_Rancic = -0.00009725109376, |A - A_Rancic| = 5.45e-15 
```

The notes at https://www.overleaf.com/4334618329ngmtbmbvjrcn describe the procedure behind the script.

### CODE REVIEW

**Comment by navidcy** [comment]
I'll also convert the script to a utility function.

**Comment by navidcy** [comment]
Rancic et al (1996) claimed that `Nφ = 128` and `r = 0.95` is adequate to give 15 decimal points. To get agreement with Rancic's coefficients up to 15 decimal points I needed to go much closer to unit circle, i.e.,
`r = 1 - 1e-7` and `Nφ = 2^22 = 4194304` (like reported above).

**Comment by glwagner** [comment]
> Rancic et al (1996) claimed that `Nφ = 128` and `r = 0.95` is adequate to give 15 decimal points. To get agreement with Rancic's coefficients up to 15 decimal points I needed to go much closer to unit circle, i.e., `r = 1 - 1e-7` and use substantially much more points than 128, namely, `Nφ = 2^22 = 4194304`!

sketchy

**Comment by navidcy** [comment]
> But if you truncate at k=30, the series is only accurate to 1e-4, right? Why do you need 15 digits in the coefficients then?

Oh I don’t truncate to 30. Only just printed out first 30. I truncated to 256 or 512. Didn’t make any difference.

**Comment by glwagner** [comment]
I think the question is: how does the series truncation + coefficient accuracy translate to errors in the grid metrics?

**Comment by navidcy** [comment]
Yes, I’ll do that and get back to you!

**Comment by navidcy** [comment]
I'll merge this since it has not changed anything in the main package but only adds functionality for computing the Taylor coefficients + fixed the scripts in sandbox directory. We can continue the discussion in #15.

**Comment by navidcy** [comment]
I added some functionality: https://clima.github.io/CubedSphere.jl/previews/PR18/library/internals/#CubedSphere

**Pull request merged**
