### PR TITLE
Increase TaylorSeries.jl compat range

### PR DESCRIPTION
**Pull request by simonbyrne**
Older versions are causing issues on Julia 1.9

### CODE REVIEW

**Comment by navidcy** [comment]
Cool. Thanks! I’ll have a look at this!

**Review by navidcy — APPROVED** [review]
lgtm!

I added explicit CI on v1.6 (LTS), v1.8 (until Oceananigans moves to v1.9), v1.9, and nightly.

**Comment by navidcy** [comment]
OK! merge at your convenience and tag Julia registrator for a new release. ;)

**Comment by simonbyrne** [comment]
Thank you!

**Pull request merged**
